# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.4_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.4_1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/will/Desktop/GSWMender

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/will/Desktop/GSWMender

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.4_1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/will/Desktop/GSWMender/CMakeFiles /Users/will/Desktop/GSWMender/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/will/Desktop/GSWMender/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gsw

# Build rule for target.
gsw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gsw
.PHONY : gsw

# fast build rule for target.
gsw/fast:
	$(MAKE) -f CMakeFiles/gsw.dir/build.make CMakeFiles/gsw.dir/build
.PHONY : gsw/fast

#=============================================================================
# Target rules for targets named Traceback

# Build rule for target.
Traceback: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Traceback
.PHONY : Traceback

# fast build rule for target.
Traceback/fast:
	$(MAKE) -f CMakeFiles/Traceback.dir/build.make CMakeFiles/Traceback.dir/build
.PHONY : Traceback/fast

#=============================================================================
# Target rules for targets named Class-Node

# Build rule for target.
Class-Node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Class-Node
.PHONY : Class-Node

# fast build rule for target.
Class-Node/fast:
	$(MAKE) -f CMakeFiles/Class-Node.dir/build.make CMakeFiles/Class-Node.dir/build
.PHONY : Class-Node/fast

#=============================================================================
# Target rules for targets named Class-GraphAlignment

# Build rule for target.
Class-GraphAlignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Class-GraphAlignment
.PHONY : Class-GraphAlignment

# fast build rule for target.
Class-GraphAlignment/fast:
	$(MAKE) -f CMakeFiles/Class-GraphAlignment.dir/build.make CMakeFiles/Class-GraphAlignment.dir/build
.PHONY : Class-GraphAlignment/fast

#=============================================================================
# Target rules for targets named Class-Alignment

# Build rule for target.
Class-Alignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Class-Alignment
.PHONY : Class-Alignment

# fast build rule for target.
Class-Alignment/fast:
	$(MAKE) -f CMakeFiles/Class-Alignment.dir/build.make CMakeFiles/Class-Alignment.dir/build
.PHONY : Class-Alignment/fast

#=============================================================================
# Target rules for targets named PileUp

# Build rule for target.
PileUp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PileUp
.PHONY : PileUp

# fast build rule for target.
PileUp/fast:
	$(MAKE) -f CMakeFiles/PileUp.dir/build.make CMakeFiles/PileUp.dir/build
.PHONY : PileUp/fast

Class-Alignment.o: Class-Alignment.cpp.o

.PHONY : Class-Alignment.o

# target to build an object file
Class-Alignment.cpp.o:
	$(MAKE) -f CMakeFiles/Class-Alignment.dir/build.make CMakeFiles/Class-Alignment.dir/Class-Alignment.cpp.o
.PHONY : Class-Alignment.cpp.o

Class-Alignment.i: Class-Alignment.cpp.i

.PHONY : Class-Alignment.i

# target to preprocess a source file
Class-Alignment.cpp.i:
	$(MAKE) -f CMakeFiles/Class-Alignment.dir/build.make CMakeFiles/Class-Alignment.dir/Class-Alignment.cpp.i
.PHONY : Class-Alignment.cpp.i

Class-Alignment.s: Class-Alignment.cpp.s

.PHONY : Class-Alignment.s

# target to generate assembly for a file
Class-Alignment.cpp.s:
	$(MAKE) -f CMakeFiles/Class-Alignment.dir/build.make CMakeFiles/Class-Alignment.dir/Class-Alignment.cpp.s
.PHONY : Class-Alignment.cpp.s

Class-GraphAlignment.o: Class-GraphAlignment.cpp.o

.PHONY : Class-GraphAlignment.o

# target to build an object file
Class-GraphAlignment.cpp.o:
	$(MAKE) -f CMakeFiles/Class-GraphAlignment.dir/build.make CMakeFiles/Class-GraphAlignment.dir/Class-GraphAlignment.cpp.o
.PHONY : Class-GraphAlignment.cpp.o

Class-GraphAlignment.i: Class-GraphAlignment.cpp.i

.PHONY : Class-GraphAlignment.i

# target to preprocess a source file
Class-GraphAlignment.cpp.i:
	$(MAKE) -f CMakeFiles/Class-GraphAlignment.dir/build.make CMakeFiles/Class-GraphAlignment.dir/Class-GraphAlignment.cpp.i
.PHONY : Class-GraphAlignment.cpp.i

Class-GraphAlignment.s: Class-GraphAlignment.cpp.s

.PHONY : Class-GraphAlignment.s

# target to generate assembly for a file
Class-GraphAlignment.cpp.s:
	$(MAKE) -f CMakeFiles/Class-GraphAlignment.dir/build.make CMakeFiles/Class-GraphAlignment.dir/Class-GraphAlignment.cpp.s
.PHONY : Class-GraphAlignment.cpp.s

Class-Node.o: Class-Node.cpp.o

.PHONY : Class-Node.o

# target to build an object file
Class-Node.cpp.o:
	$(MAKE) -f CMakeFiles/Class-Node.dir/build.make CMakeFiles/Class-Node.dir/Class-Node.cpp.o
.PHONY : Class-Node.cpp.o

Class-Node.i: Class-Node.cpp.i

.PHONY : Class-Node.i

# target to preprocess a source file
Class-Node.cpp.i:
	$(MAKE) -f CMakeFiles/Class-Node.dir/build.make CMakeFiles/Class-Node.dir/Class-Node.cpp.i
.PHONY : Class-Node.cpp.i

Class-Node.s: Class-Node.cpp.s

.PHONY : Class-Node.s

# target to generate assembly for a file
Class-Node.cpp.s:
	$(MAKE) -f CMakeFiles/Class-Node.dir/build.make CMakeFiles/Class-Node.dir/Class-Node.cpp.s
.PHONY : Class-Node.cpp.s

PileUp.o: PileUp.cpp.o

.PHONY : PileUp.o

# target to build an object file
PileUp.cpp.o:
	$(MAKE) -f CMakeFiles/PileUp.dir/build.make CMakeFiles/PileUp.dir/PileUp.cpp.o
.PHONY : PileUp.cpp.o

PileUp.i: PileUp.cpp.i

.PHONY : PileUp.i

# target to preprocess a source file
PileUp.cpp.i:
	$(MAKE) -f CMakeFiles/PileUp.dir/build.make CMakeFiles/PileUp.dir/PileUp.cpp.i
.PHONY : PileUp.cpp.i

PileUp.s: PileUp.cpp.s

.PHONY : PileUp.s

# target to generate assembly for a file
PileUp.cpp.s:
	$(MAKE) -f CMakeFiles/PileUp.dir/build.make CMakeFiles/PileUp.dir/PileUp.cpp.s
.PHONY : PileUp.cpp.s

Traceback.o: Traceback.cpp.o

.PHONY : Traceback.o

# target to build an object file
Traceback.cpp.o:
	$(MAKE) -f CMakeFiles/Traceback.dir/build.make CMakeFiles/Traceback.dir/Traceback.cpp.o
.PHONY : Traceback.cpp.o

Traceback.i: Traceback.cpp.i

.PHONY : Traceback.i

# target to preprocess a source file
Traceback.cpp.i:
	$(MAKE) -f CMakeFiles/Traceback.dir/build.make CMakeFiles/Traceback.dir/Traceback.cpp.i
.PHONY : Traceback.cpp.i

Traceback.s: Traceback.cpp.s

.PHONY : Traceback.s

# target to generate assembly for a file
Traceback.cpp.s:
	$(MAKE) -f CMakeFiles/Traceback.dir/build.make CMakeFiles/Traceback.dir/Traceback.cpp.s
.PHONY : Traceback.cpp.s

gsw.o: gsw.cpp.o

.PHONY : gsw.o

# target to build an object file
gsw.cpp.o:
	$(MAKE) -f CMakeFiles/gsw.dir/build.make CMakeFiles/gsw.dir/gsw.cpp.o
.PHONY : gsw.cpp.o

gsw.i: gsw.cpp.i

.PHONY : gsw.i

# target to preprocess a source file
gsw.cpp.i:
	$(MAKE) -f CMakeFiles/gsw.dir/build.make CMakeFiles/gsw.dir/gsw.cpp.i
.PHONY : gsw.cpp.i

gsw.s: gsw.cpp.s

.PHONY : gsw.s

# target to generate assembly for a file
gsw.cpp.s:
	$(MAKE) -f CMakeFiles/gsw.dir/build.make CMakeFiles/gsw.dir/gsw.cpp.s
.PHONY : gsw.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gsw"
	@echo "... Traceback"
	@echo "... Class-Node"
	@echo "... Class-GraphAlignment"
	@echo "... Class-Alignment"
	@echo "... PileUp"
	@echo "... Class-Alignment.o"
	@echo "... Class-Alignment.i"
	@echo "... Class-Alignment.s"
	@echo "... Class-GraphAlignment.o"
	@echo "... Class-GraphAlignment.i"
	@echo "... Class-GraphAlignment.s"
	@echo "... Class-Node.o"
	@echo "... Class-Node.i"
	@echo "... Class-Node.s"
	@echo "... PileUp.o"
	@echo "... PileUp.i"
	@echo "... PileUp.s"
	@echo "... Traceback.o"
	@echo "... Traceback.i"
	@echo "... Traceback.s"
	@echo "... gsw.o"
	@echo "... gsw.i"
	@echo "... gsw.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

